config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :links
    resources :categories
  end
  # mount Fae below your admin namespec
  mount Fae::Engine => '/admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  include Fae::BaseModelConcern

  acts_as_list add_new_at: :top
  default_scope { order(:position) }

  def fae_display_field
    name
  end

  has_many :links
end

app/models/concerns/fae/authorization_concern.rb
module Fae
  module AuthorizationConcern
    extend ActiveSupport::Concern
    module ClassMethods

      # Use the access_map to define any controllers that need any special authorization
      # Fae comes with three default roles:
      # - super admin: CRUD all objects, INCLUDING users and root settings
      # - admin: CRUD all objects, INCLUDING users and EXCLUDING root settings
      # - users: CRUD all objects, EXCLUDING users and root settings

      # each item should have a string key of the plural controller name and
      # an array of role names for the value
      # use "content_blocks/#{page_name}" for content blocks

      # example:
      # {
      #  'people' => ['super admin', 'admin'],
      #  'content_blocks/about_us' => ['super admin']
      # }
      def access_map
        {}
      end

    end
  end
end

app/models/concerns/fae/navigation_concern.rb
module Fae
  module NavigationConcern
    extend ActiveSupport::Concern

    # define the navigation structure in this file
    # example structure:
    #
    # def structure
    #   [
    #     item('Top Nav Item 1', subitems: [
    #       item('Top Nav Dropdown Item 1', class: 'custom-class', path: some_named_route_path),
    #       item('Top Nav Dropdown Item 2', subitems: [
    #         item('Side Nav Item 1', subitems: [
    #           item('Side Nav Nested Item', path: some_named_route_path)
    #         ]),
    #         item('Side Nav Item 1', path: some_named_route_path)
    #       ]),
    #     ]),
    #     item('Pages', subitems: [
    #       item('Home', path: fae.edit_content_block_path('home')),
    #       item('About Us', path: fae.edit_content_block_path('about_us'))
    #     ])
    #   ]
    # end

    def structure
      [
        item('Categories', path: admin_categories_path),
        # scaffold inject marker
      ]
    end

  end
end

app/models/link.rb
class Link < ApplicationRecord
  include Fae::BaseModelConcern

  belongs_to :category, touch: true

  def fae_nested_parent
    :category
  end

  acts_as_list add_new_at: :top
  default_scope { order(:position) }

  def fae_display_field
    title
  end

  belongs_to :category
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Fae::BaseController

  end
end

app/controllers/admin/links_controller.rb
module Admin
  class LinksController < Fae::NestedBaseController

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_form.html.slim
= simple_form_for(['admin', @item]) do |f|
  == render 'fae/shared/form_header', header: @klass_name

  main.content
    = fae_input f, :name

app/views/admin/categories/edit.html.slim
== render 'form'

== render 'fae/shared/nested_table', assoc: :links, parent_item: @item, cols: [:position, :title, :description], title: "Links For You", ordered: true

app/views/admin/categories/index.html.slim
== render 'fae/shared/index_header', title: @klass_humanized.pluralize.titleize

main.content
  table.js-sort-row
    thead
      tr
        th.th-sortable-handle
        th Name
        th.-action-wide Modified
        th.-action data-sorter="false"

    tbody
      - if @items.present?
        - @items.each do |item|
          tr id=fae_sort_id(item)
            td.sortable-handle: i.icon-sort
            td = link_to item.fae_display_field, edit_admin_category_path(item)
            td = fae_date_format item.updated_at
            td = fae_delete_button item
      - else
        tr: td colspan="4" No items found

app/views/admin/categories/new.html.slim
== render 'form'

app/views/admin/links/_form.html.slim
= simple_form_for(['admin', @item], html: {multipart: true, novalidate: true, class: 'js-file-form'}, remote: true, data: {type: "html"}) do |f|
  = fae_input f, :title
  = fae_input f, :description

  = f.hidden_field :category_id

  = f.submit
  = button_tag 'Cancel', type: 'button', class: 'js-cancel-nested cancel-nested-button'

app/views/admin/links/edit.html.slim
.nested-form
  h2 Edit Link
  == render 'form'

app/views/admin/links/new.html.slim
.nested-form
  h2 New Link
  == render 'form'

app/views/admin/links/table.html.slim
== render 'fae/shared/nested_table',
  assoc: :links,
  parent_item: @parent_item,
  cols: [:title, :description]

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestNestedFormsFaecms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>